package com.luxoft.trainings.jva005.day_3;

import java.io.IOException;
import java.sql.*;
import java.util.Properties;

public class AutogeneratedPrimaryKeysExample {

    public static void main(String[] args) throws IOException, SQLException {
        Properties dbProperties = new Properties();
        dbProperties.load(AutogeneratedPrimaryKeysExample.class.getResourceAsStream("/db.properties"));

        try (Connection conn = DriverManager.getConnection(dbProperties.getProperty("url"), dbProperties);
             PreparedStatement stmt = conn.prepareStatement("INSERT INTO shop.users (name, address, username, password, accesslevel)" +
                                                                " VALUES ('NAME_1', 'ADDRESS_1', 'USERNAME_1', 'PASSWORD_1', 0)", Statement.RETURN_GENERATED_KEYS)) {

            if (stmt.executeUpdate() != 1) {
                throw new SQLException();
            }

            try (ResultSet rs = stmt.getGeneratedKeys()) {
                while (rs.next()) {
                    System.out.println(rs.getLong("userid"));
                }
            }

        }
    }
}
